In [1]:
import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re
import warnings
from pathlib import Path

from voltage_divider_data import load_all_data

In [2]:
data = load_all_data()
list(vars(data))
## data = load_all_data(include_intermediate=True) include "raw" pandas dataframes - for debugging purposes only

['measurement_df', 'sim_df', 'comparison_df']

In [3]:
data.sim_df

simulation_setting,20,100,200,300,400,500,600,700,800,900,1000,pins
pins,,,,,,,,,,,,
HV,20.00000,100.0000,200.0000,300.0000,400.000,500.000,600.000,700.000,800.000,900.000,1000.000,HV
K-G,0.80000,4.0000,8.0000,12.0000,16.000,20.000,24.000,28.000,32.000,36.000,40.000,K-G
K-Dy1,3.20000,16.0000,32.0000,48.0000,64.000,80.000,96.000,112.000,128.000,144.000,160.000,K-Dy1
K-Dy2,6.32727,31.6364,63.2727,94.9091,126.545,158.182,189.818,221.455,253.091,284.727,316.364,K-Dy2
K-Dy3,7.92727,39.6364,79.2727,118.9090,158.545,198.182,237.818,277.455,317.091,356.727,396.364,K-Dy3
K-Dy4,9.52727,47.6364,95.2727,142.9090,190.545,238.182,285.818,333.455,381.091,428.727,476.364,K-Dy4
K-Dy5,11.12730,55.6364,111.2730,166.9090,222.545,278.182,333.818,389.455,445.091,500.727,556.364,K-Dy5
K-Dy6,12.72730,63.6364,127.2730,190.9090,254.545,318.182,381.818,445.455,509.091,572.727,636.364,K-Dy6
K-Dy7,14.32730,71.6364,143.2730,214.9090,286.545,358.182,429.818,501.455,573.091,644.727,716.364,K-Dy7
K-Dy8,15.92730,79.6364,159.2730,238.9090,318.545,398.182,477.818,557.455,637.091,716.727,796.364,K-Dy8
K-Dy9,17.52730,87.6364,175.2730,262.9090,350.545,438.182,525.818,613.455,701.091,788.727,876.364,K-Dy9
K-Dy10,19.12730,95.6364,191.2730,286.9090,382.545,478.182,573.818,669.455,765.091,860.727,956.364,K-Dy10
K-P,19.92730,99.6364,199.2730,298.9090,398.545,498.182,597.818,697.455,797.091,896.727,996.364,K-P

In [4]:
data.measurement_df

,input_voltage_V,measured_between,measured_voltage_V,computed_between,cumulative_voltage_from_K_V
0,50.0,K-G,1.826,K-G,1.826
1,50.0,G-Dy1,5.894,K-Dy1,7.720
2,50.0,Dy1-Dy2,7.600,K-Dy2,15.320
3,50.0,Dy2-Dy3,3.943,K-Dy3,19.263
4,50.0,Dy3-Dy4,3.933,K-Dy4,23.196
...,...,...,...,...,...
127,1000.0,Dy6-Dy7,78.400,K-Dy7,696.740
128,1000.0,Dy7-Dy8,78.600,K-Dy8,775.340
129,1000.0,Dy8-Dy9,78.400,K-Dy9,853.740
130,1000.0,Dy9-Dy10,78.400,K-Dy10,932.140
131,1000.0,Dy10-P,39.100,K-P,971.240

In [6]:
data.comparison_df

,input_voltage_V,pins,measured_voltage_V,simulated_voltage_V,delta_V,delta_percent
0,100.0,K-G,3.647,4.000,-0.353,-8.825000
1,200.0,K-G,7.230,8.000,-0.770,-9.625000
2,300.0,K-G,10.830,12.000,-1.170,-9.750000
3,400.0,K-G,14.430,16.000,-1.570,-9.812500
4,500.0,K-G,18.040,20.000,-1.960,-9.800000
...,...,...,...,...,...,...
115,600.0,K-P,582.670,597.818,-15.148,-2.533882
116,700.0,K-P,679.800,697.455,-17.655,-2.531346
117,800.0,K-P,777.010,797.091,-20.081,-2.519286
118,900.0,K-P,873.950,896.727,-22.777,-2.540015
119,1000.0,K-P,971.240,996.364,-25.124,-2.521568